n = input('Digite algo')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaço?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabetico?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Ésta em maiúsculas?', n.isupper())
print('Ésta em minúsculas', n.islower())
print('Está capitalizada', n.istitle())
